// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { Builder } = require('selenium-webdriver');

describe('A negative number minus a negative number.', function() {
  this.timeout(30000)
  let vars
  let driver = new Builder()
    .forBrowser('chrome')
    .setChromeService(new chrome.ServiceBuilder('/usr/local/bin/chromedriver'))
    .build();

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('A negative number minus a negative number.', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect(1051, 797)
    await driver.findElement(By.linkText("src/")).click()
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("-5")
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("-5")
    await driver.findElement(By.css("button:nth-child(2)")).click()
  })
})
