// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { Builder } = require('selenium-webdriver');

describe('Empty screen minus any number', function() {
  this.timeout(30000)
  let vars

  let driver = new Builder()
    .forBrowser('chrome')
    .setChromeService(new chrome.ServiceBuilder('/usr/local/bin/chromedriver'))
    .build();

  afterEach(async function() {
    await driver.quit();
  })
  it('Empty screen minus any number', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect(789, 817)
    await driver.findElement(By.linkText("src/")).click()
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("2")
    await driver.findElement(By.css("button:nth-child(2)")).click()
  })
})
