// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const edge = require('selenium-webdriver/edge')
const assert = require('assert')

describe('Empty screen minus any number', function() {
  this.timeout(30000)
  let driver
  let vars
  
  beforeEach(async function() {
    // Set up Edge options
    const options = new edge.Options()
    options.addArguments('--headless', '--disable-gpu', '--no-sandbox')
    
    // Create Edge service
    const service = new edge.ServiceBuilder()
      .setPath(process.env.EDGEWEBDRIVER || '/usr/local/bin/msedgedriver')
      .build()
    
    // Build the driver with Edge configuration
    driver = await new Builder()
      .forBrowser('MicrosoftEdge')
      .setEdgeOptions(options)
      .setEdgeService(service)
      .build()
      
    vars = {}
  })
  
  afterEach(async function() {
    if (driver) {
      await driver.quit()
    }
  })
  
  it('Empty screen minus any number', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect(789, 817)
    await driver.findElement(By.linkText("src/")).click()
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("2")
    await driver.findElement(By.css("button:nth-child(2)")).click()
  })
})
