// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('In an operation, if you click equal multiple times.', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('In an operation, if you click equal multiple times.', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect(1051, 797)
    await driver.findElement(By.linkText("src/")).click()
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("5")
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("5")
    await driver.findElement(By.css("button:nth-child(2)")).click()
    await driver.findElement(By.css("button:nth-child(2)")).click()
    await driver.findElement(By.css("button:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css("button:nth-child(2)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("button:nth-child(2)")).click()
  })
})
