name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 120
        install-dependencies: true

    - name: Verify Chrome Installation
      run: google-chrome --version

    - name: Install Dependencies
      run: npm install
      working-directory: ./tests

    - name: Start Web Server
      run: python3 -m http.server 8000 &  
      working-directory: ./src

    - name: Run Selenium Tests
      run: |
        ./node_modules/.bin/mocha *.js
      working-directory: ./tests
      env:
        CHROME_BIN: /usr/bin/google-chrome
        SELENIUM_BROWSER: chrome
