name: Run Selenium Tests

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Selenium tests
        run: |
          npm install selenium-webdriver
          npm test
