name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: npm start &

    - name: Wait for server to be ready
      run: |
        until curl --output /dev/null --silent --head --fail http://localhost:8000; do
          sleep 1
        done

    - name: Run tests
      run: curl http://localhost:8000
