name: Run Selenium Tests with Mocha and Edge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install
        npm install -g mocha
        npm install selenium-webdriver

    - name: Install Microsoft Edge
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/
        sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
        sudo rm microsoft.gpg
        sudo apt-get update
        sudo apt-get install microsoft-edge-dev

    - name: Download Microsoft Edge WebDriver
      run: |
        EDGE_VERSION=$(microsoft-edge --version | cut -d' ' -f3)
        EDGE_DRIVER_VERSION=$(curl -s https://msedgedriver.azureedge.net/LATEST_RELEASE_$EDGE_VERSION)
        wget https://msedgedriver.azureedge.net/$EDGE_DRIVER_VERSION/edgedriver_linux64.zip
        unzip edgedriver_linux64.zip -d /usr/local/bin
        chmod +x /usr/local/bin/msedgedriver

    - name: Start HTTP server
      run: |
        python -m http.server 8000 &

    - name: Run Mocha tests
      run: |
        export PATH=$PATH:/usr/local/bin
        mocha tests/ --timeout 10000
