name: Run tests

on:
  workflow_dispatch:
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:20

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=3gb

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: cd tests
      - run: npm install
      - run: ./node_modules/.bin/mocha *.js
      
      - name: Check Docker container health
        run: docker ps -a

      - name: Display Selenium logs
        run: docker logs $(docker ps -q -f ancestor=selenium/standalone-chrome)
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
