name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set execute permissions for Mocha
        run: chmod +x ./node_modules/.bin/mocha

      - name: Install Python (required for http.server)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      - name: Start Python server and run tests
        run: |
          cd src
          python -m http.server 8000 &
          sleep 10
          curl http://localhost:8000
          cd ..
          cd tests
          ./node_modules/.bin/mocha test1.spec.js

      - name: Upload screenshots (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
