name: Run tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start Python server and run tests
        run: |
          cd src
          python3 -m http.server 8000 &
          sleep 10
          curl http://localhost:8000
          cd ..
          cd tests
          ./node_modules/.bin/mocha test1.spec.js

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
